# Generated by Django 5.1.4 on 2024-12-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_service_doctor_category_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
