# Generated by Django 5.1.4 on 2025-02-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
    ]
