# Generated by Django 5.1.6 on 2025-12-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_prescription_prescription_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
