# Generated by Django 5.1.6 on 2025-05-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_image",
        ),
    ]
