# Generated by Django 5.1.6 on 2025-12-31 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_address_customuser_full_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "sugar_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("bp_systolic", models.PositiveIntegerField(blank=True, null=True)),
                ("bp_diastolic", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "sleep",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("mood", models.CharField(blank=True, max_length=50, null=True)),
                ("steps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "water",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("calorie", models.PositiveIntegerField(blank=True, null=True)),
                ("temperature_done", models.BooleanField(default=False)),
                ("sugar_done", models.BooleanField(default=False)),
                ("bp_done", models.BooleanField(default=False)),
                ("weight_done", models.BooleanField(default=False)),
                ("sleep_done", models.BooleanField(default=False)),
                ("mood_done", models.BooleanField(default=False)),
                ("steps_done", models.BooleanField(default=False)),
                ("water_done", models.BooleanField(default=False)),
                ("calorie_done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
