# Generated by Django 5.1.6 on 2025-12-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_dailyrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyRecord",
        ),
    ]
