# Generated by Django 5.1.6 on 2025-12-31 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "sugar_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("bp_systolic", models.IntegerField(blank=True, null=True)),
                ("bp_diastolic", models.IntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "sleep_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("mood", models.CharField(blank=True, max_length=50, null=True)),
                ("steps", models.IntegerField(blank=True, null=True)),
                (
                    "water_liters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("calorie", models.IntegerField(blank=True, null=True)),
                ("tick_temperature", models.BooleanField(default=False)),
                ("tick_sugar_level", models.BooleanField(default=False)),
                ("tick_bp", models.BooleanField(default=False)),
                ("tick_weight", models.BooleanField(default=False)),
                ("tick_sleep", models.BooleanField(default=False)),
                ("tick_mood", models.BooleanField(default=False)),
                ("tick_steps", models.BooleanField(default=False)),
                ("tick_water", models.BooleanField(default=False)),
                ("tick_calorie", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
