# Generated by Django 6.0 on 2025-12-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
