# Generated by Django 6.0 on 2025-12-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_dailyrecord_reminder_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyrecord",
            name="reminder_sent",
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="reminder_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
