# Generated by Django 5.1.6 on 2025-05-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
