# Generated by Django 5.1.6 on 2025-05-17 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_doctor_specialist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="available_time",
            field=models.CharField(default="9:00 AM - 5:00 PM", max_length=100),
        ),
        migrations.AddField(
            model_name="doctor",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="consultation_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="doctor",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(upload_to="doctors/"),
        ),
    ]
