# Generated by Django 5.1.6 on 2025-12-19 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_order_items"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripe_payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="api.order",
            ),
        ),
    ]
