# Generated by Django 5.1.6 on 2025-05-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_doctor_available_time_doctor_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="user",
        ),
    ]
