# Generated by Django 5.1.3 on 2024-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productImage",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
