# Generated by Django 5.1.4 on 2025-02-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
